---
driver:
  name: docker
platforms:
  - name: ubuntu2004
    image: docker.io/geerlingguy/docker-ubuntu2404-ansible
  # - name: oracle
  #   image: docker.io/debian:12
  # - name: ubuntu24
  #   image: docker.io/ubuntu:24.04
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    - dependency
    # - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    # - destroy
